<?php

const CLIENT_NAME = '%CLIENT_NAME%';
const CLIENT_PHONE = '%CLIENT_PHONE%';
const CLIENT_EMAIL = '%CLIENT_EMAIL%';

const COMMENT = '%COMMENT%';

const CEILING_LENGTH = '%CEILING_LENGTH%';
const CEILING_WIDTH = '%CEILING_WIDTH%';
const CORNERS = '%CORNERS%';
const PRIMARY_LIGHT = '%PRIMARY_LIGHT%';
const SECONDARY_LIGHTS = '%SECONDARY_LIGHTS%';
const TUBES = '%TUBES%';

const COMMENT_BODY = '%COMMENT_BODY%';

const ADDITIONAL_BODY = '%ADDITIONAL_BODY%';
